### ISSUE TITLE
YouTube download error workaround

### ISSUE THREAD

**Issue by cccaaannn** [cccaaannn/telegram_youtube_downloader#12]
If you are deploying the bot for personal usage, and having problems with YouTube even with your cookies you can try this workaround.

The idea is, if your legitimate traffic is also coming from the same IP with same cookies YouTube cannot tell the difference.
1. Install a vpn server to the server that you will use for the telegram downloader bot.
2. Connect to vpn from your local machine and use your YouTube account for some time, you don't need to use it forever with vpn.
3. Export your cookies file.
4. Run the bot on that server with your cookie file.

Any vpn would work, I used [dockovpn](https://github.com/dockovpn/dockovpn) on my tests.

**Comment by PRIHLOP** [comment]
Or you can add to the config the following lines(to use HTTP proxy instead VPN):

```yaml
  audio_options:                                  # audio_options are directly passed to youtube_dl on audio downloads
    proxy: "10.10.10.10:3128"             # replace by your proxy server address

  video_options:                                  # video_options are directly passed to youtube_dl on video downloads
    proxy: "10.10.10.10:3128"            # replace by your proxy server address
```

Also, possible to use `extractor_args` to get a video without cookies(better to use with a proxy, but it is optional):

```yaml
  audio_options:                                  # audio_options are directly passed to youtube_dl on audio downloads
    extractor_args: '"youtubetab:skip=webpage;youtube:player_skip=webpage,configs;visitor_data=<VISITOR_DATA>;youtube:po_token=web.gvs+<PO_TOKEN>"'
    proxy: "10.10.10.10:3128"            # replace by your proxy server address

  video_options:                                  # video_options are directly passed to youtube_dl on video downloads
    extractor_args: '"youtubetab:skip=webpage;youtube:player_skip=webpage,configs;visitor_data=<VISITOR_DATA>;youtube:po_token=web.gvs+<PO_TOKEN>"'
    proxy: "10.10.10.10:3128"            # replace by your proxy server address
```
Information about getting these parameters can be found there -> [YouTube trusted session generator](https://github.com/iv-org/youtube-trusted-session-generator).
